### ISSUE TITLE
Licence required

### ISSUE THREAD

**Issue by Julie-House** [bajceticnenad/Cyrillic.Convert#3]
Please can you add a licence to this project? We've found this project useful but won't be able to continue using it without a valid licence. 
Thanks

**Comment by bajceticnenad** [comment]
Hi,
I added an MIT license to the project. Is it necessary on Nuget.org or is this enough?

Best Regards,
Nenad

**Comment by Julie-House** [comment]
Ideally, yes it needs to be on Nuget please. From what i can tell the software we use to analyze dependencies checks the link that Nuget requires to be populated.

**Comment by bajceticnenad** [comment]
Hi,
MIT license added in version 2.2.1
